/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pencer.accounts;

/**
 *
 * @author maina
 */
public class EditIncomeAccountsDetails extends javax.swing.JInternalFrame {

    private javax.swing.JDesktopPane desktopPane=null;
    private java.sql.Connection connection=null;
    private com.pencer.search.SearchDialog sd=null;
    /**
     * Creates new form IncomeAccounts
     */
    public EditIncomeAccountsDetails(java.sql.Connection conn, javax.swing.JDesktopPane jdp) {
        
        connection=conn;
        desktopPane=jdp;
        desktopPane.add(this);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        motherjPanel = new javax.swing.JPanel();
        detailsjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        acNamejTextField = new javax.swing.JTextField();
        acNojTextField = new javax.swing.JTextField();
        parentjTextField = new javax.swing.JTextField();
        feejTextField = new javax.swing.JTextField();
        buttonsjPanel = new javax.swing.JPanel();
        createjButton = new javax.swing.JButton();
        closejButton = new javax.swing.JButton();
        clearjButton = new javax.swing.JButton();
        searchjPanel = new javax.swing.JPanel();
        searchjTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Income Account Details");
        setPreferredSize(new java.awt.Dimension(700, 310));
        setVisible(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        motherjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(0));
        motherjPanel.setLayout(new java.awt.GridBagLayout());

        detailsjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        detailsjPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Account Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 12, 0);
        detailsjPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Parent Institution");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 12, 0);
        detailsjPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Account No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        detailsjPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Withdrawal Fee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        detailsjPanel.add(jLabel4, gridBagConstraints);

        acNamejTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
        detailsjPanel.add(acNamejTextField, gridBagConstraints);

        acNojTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        detailsjPanel.add(acNojTextField, gridBagConstraints);

        parentjTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
        detailsjPanel.add(parentjTextField, gridBagConstraints);

        feejTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        detailsjPanel.add(feejTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 12, 12);
        motherjPanel.add(detailsjPanel, gridBagConstraints);

        buttonsjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonsjPanel.setLayout(new java.awt.GridBagLayout());

        createjButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        createjButton.setText("Update Account");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        buttonsjPanel.add(createjButton, gridBagConstraints);

        closejButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        closejButton.setText("Close");
        closejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closejButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        buttonsjPanel.add(closejButton, gridBagConstraints);

        clearjButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        clearjButton.setText("Clear Fields");
        clearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        buttonsjPanel.add(clearjButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        motherjPanel.add(buttonsjPanel, gridBagConstraints);

        searchjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchjPanel.setLayout(new java.awt.GridBagLayout());

        searchjTextField.setEditable(false);
        searchjTextField.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        searchjPanel.add(searchjTextField, gridBagConstraints);

        searchjButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        searchjPanel.add(searchjButton, gridBagConstraints);

        jLabel5.setText("Account ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        searchjPanel.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        motherjPanel.add(searchjPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(motherjPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:
        
        if(acNamejTextField.getText()==null||acNamejTextField.getText().length()<1||
                acNojTextField.getText()==null||acNojTextField.getText().length()<1||
                feejTextField.getText()==null||feejTextField.getText().length()<1||
                parentjTextField.getText()==null||parentjTextField.getText().length()<1||
                searchjTextField.getText()==null||searchjTextField.getText().length()<1){
            
            javax.swing.JOptionPane.showMessageDialog(this, "Please ensure that all the fields have valid data!",
                    "Error on save!",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            
            try{
                connection.setAutoCommit(false);
            
                java.sql.PreparedStatement updatePs=connection.prepareStatement("UPDATE income_accounts SET account_name=?, account_no=?, bank=?, withdrawal_fee=? WHERE account_id='"+searchjTextField.getText()+"'");
            
                updatePs.setString(1, acNamejTextField.getText());
                updatePs.setString(2, acNojTextField.getText());
                updatePs.setString(3, parentjTextField.getText());
                updatePs.setString(4, feejTextField.getText());
                
                updatePs.executeUpdate();
            
                connection.commit();
                connection.setAutoCommit(true);
            
                javax.swing.JOptionPane.showMessageDialog(this, "Account details updated successfully!",
                        "Update Successful!",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
                clearjButton.doClick();
            
            }catch(java.sql.SQLException sqle){
                System.err.println("Commit error!");
            
                sqle.printStackTrace();
            
                try{
                    connection.rollback();
                    connection.setAutoCommit(true);
                
                }catch(java.sql.SQLException sqlex){
                
                    System.err.println("Rollback error!");
                    sqlex.printStackTrace();
                }
                
            
            }
            
        }
        
    }//GEN-LAST:event_createjButtonActionPerformed

    private void closejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closejButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closejButtonActionPerformed

    private void clearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButtonActionPerformed
        // TODO add your handling code here:
        acNamejTextField.setText("");
        acNojTextField.setText("");
        feejTextField.setText("");
        parentjTextField.setText("");
        searchjTextField.setText("");
    }//GEN-LAST:event_clearjButtonActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Point point=searchjTextField.getLocationOnScreen();
        
        sd=new com.pencer.search.SearchDialog(true, connection,
                                        "SELECT account_id, account_name, account_no FROM income_accounts ",
                                        "WHERE account_name LIKE '%",
                                        "%' ORDER BY account_name " );
        
        sd.addSearchDialogListener(new javax.swing.event.ListSelectionListener(){
            
            int selectedIndex=-1;
            
            public void valueChanged(javax.swing.event.ListSelectionEvent lse){
                
                selectedIndex=sd.getSearchJTable().getSelectionModel().getMinSelectionIndex();
                
                searchjTextField.setText(sd.getSearchJTable().getValueAt(selectedIndex, 0).toString());
                acNamejTextField.setText(sd.getSearchJTable().getValueAt(selectedIndex, 1).toString());
                acNojTextField.setText(sd.getSearchJTable().getValueAt(selectedIndex, 2).toString());
                
                try{
                    java.sql.Statement stat=connection.createStatement();
                    java.sql.ResultSet bankWthSet=stat.executeQuery("SELECT bank, withdrawal_fee FROM income_accounts WHERE account_id='"+searchjTextField.getText()+"'");
                    
                    while(bankWthSet.next()){
                        parentjTextField.setText(bankWthSet.getString(1));
                        feejTextField.setText(bankWthSet.getString(2));
                    }
                    
                }catch(java.sql.SQLException sqle){
                    sqle.printStackTrace();
                }
                
                sd.dispose();
            }
        });

        sd.setLocation(point);
        sd.setVisible(true);
    }//GEN-LAST:event_searchjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acNamejTextField;
    private javax.swing.JTextField acNojTextField;
    private javax.swing.JPanel buttonsjPanel;
    private javax.swing.JButton clearjButton;
    private javax.swing.JButton closejButton;
    private javax.swing.JButton createjButton;
    private javax.swing.JPanel detailsjPanel;
    private javax.swing.JTextField feejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel motherjPanel;
    private javax.swing.JTextField parentjTextField;
    private javax.swing.JButton searchjButton;
    private javax.swing.JPanel searchjPanel;
    private javax.swing.JTextField searchjTextField;
    // End of variables declaration//GEN-END:variables
}
