/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pencer.search;

/**
 *
 * @author maina
 */
public class SearchDialog extends javax.swing.JDialog {

    //private javax.swing.JDesktopPane desktopPane=null;
    
    private java.lang.String dbQuery,whereClause,orderBy;
    //private java.lang.String column1,column2;
    
    private java.lang.String critical;
    
    private java.sql.Connection connection=null;
    
    /**
     * Creates new form SearchDialog
     */
    public SearchDialog(boolean modal, java.sql.Connection conn, java.lang.String query, java.lang.String where, java.lang.String sortBy) {
        //super(parent, modal);
        
        connection=conn;
        dbQuery=query;
        whereClause=where;
        orderBy=sortBy;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchjPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textFieldjPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        buttonjPanel1 = new javax.swing.JPanel();
        closejButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        setModal(true);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        searchjPanel1.setBackground(new java.awt.Color(178, 255, 255));
        searchjPanel1.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        searchjPanel1.add(jScrollPane1, gridBagConstraints);

        jTextField1.setColumns(10);
        jTextField1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textFieldjPanel1Layout = new javax.swing.GroupLayout(textFieldjPanel1);
        textFieldjPanel1.setLayout(textFieldjPanel1Layout);
        textFieldjPanel1Layout.setHorizontalGroup(
            textFieldjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(textFieldjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(textFieldjPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        textFieldjPanel1Layout.setVerticalGroup(
            textFieldjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(textFieldjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(textFieldjPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        searchjPanel1.add(textFieldjPanel1, gridBagConstraints);

        closejButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        closejButton1.setText("Close Panel");
        closejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonjPanel1Layout = new javax.swing.GroupLayout(buttonjPanel1);
        buttonjPanel1.setLayout(buttonjPanel1Layout);
        buttonjPanel1Layout.setHorizontalGroup(
            buttonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(buttonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonjPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(closejButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buttonjPanel1Layout.setVerticalGroup(
            buttonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(buttonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonjPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(closejButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 12, 12);
        searchjPanel1.add(buttonjPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(searchjPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closejButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closejButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:
        
        com.pencer.model.QueryTableModel qtm=new com.pencer.model.QueryTableModel(connection,
                dbQuery+whereClause+jTextField1.getText()+orderBy );
        int c=qtm.getColumnCount();
        Class[] types=new Class[c];
        boolean[] edits=new boolean[c];
        
        for(int x=0;x<types.length;x++){
            types[x]=Object.class;
            edits[x]=false;
        }
        
        qtm.setColumnClass(types);
        qtm.setCanEdit(edits);
        
        jTable1.setModel(qtm);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

//    public void completeQueryClauses(String table,String where,String sortBy){
//        tableName=table;
//        whereClause=where;
//        orderBy=sortBy;
//    }
//    
//    public void declare2ColumnsToDisplay(String col1, String col2){
//        column1=col1;
//        column2=col2;
//    }
//    
//    public String getCritical(){
//        return critical;
//    }
    public javax.swing.JTable getSearchJTable(){
        return jTable1;
    }
    
    public void addSearchDialogListener(javax.swing.event.ListSelectionListener lse){
        jTable1.getSelectionModel().addListSelectionListener(lse);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonjPanel1;
    private javax.swing.JButton closejButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel searchjPanel1;
    private javax.swing.JPanel textFieldjPanel1;
    // End of variables declaration//GEN-END:variables
}
